{% set name = "python-louvain" %}
{% set version = "0.15" %}
{% set sha256 = "2a856edfbe29952a60a5538a84bb78cca18f6884a88b9325e85a11c8dd4917eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - networkx
    - numpy

test:
  imports:
    - community

about:
  home: https://github.com/taynaud/python-louvain
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Louvain Community Detection
  description: |
    This module implements community detection.

    It uses the louvain method described in Fast unfolding of communities in
    large networks, Vincent D Blondel, Jean-Loup Guillaume, Renaud Lambiotte,
    Renaud Lefebvre, Journal of Statistical Mechanics: Theory and Experiment
    2008(10), P10008 (12pp)

  doc_url: https://python-louvain.readthedocs.io/en/latest/
  dev_url: https://github.com/taynaud/python-louvain

extra:
  recipe-maintainers:
    - ericmjl
    - MridulS
